// Command xpressgen regenerates parser/xpress_test_data.go. The plain
// LZ77 vectors are produced with an encoder that follows the MS-XCA
// section 2.1.1 pseudocode; the LZ77+Huffman vectors are spliced in
// verbatim from huffman_vectors.txt (hand-maintained fixtures).
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

type vector struct {
	name          string
	input         []byte
	expected      []byte
	huff          bool
	precompressed bool
}

func main() {
	var vecs []vector
	vecs = append(vecs, plainVectors()...)
	vecs = append(vecs, extraPlainVectors()...)
	vecs = append(vecs, sharedHalfByteVector())
	vecs = append(vecs, anchorVector())

	var b strings.Builder
	b.WriteString("// Code generated by tests/xpressgen; DO NOT EDIT.\n")
	b.WriteString("// The plain LZ77 vectors are generated with a spec-faithful\n")
	b.WriteString("// encoder (MS-XCA 2.1.1). The LZ77+Huffman vectors are\n")
	b.WriteString("// hand-maintained fixtures (see tests/xpressgen).\n")
	b.WriteString("package parser\n\n")
	b.WriteString("type xpressVector struct {\n")
	b.WriteString("\tname           string\n")
	b.WriteString("\tdata, expected []byte\n")
	b.WriteString("\thuff           bool\n")
	b.WriteString("}\n\n")
	b.WriteString("var xpressVectors = []xpressVector{\n")
	for _, v := range vecs {
		data := v.input
		if !v.precompressed {
			data = encode(v.input)
		}
		fmt.Fprintf(&b, "\t{%q, []byte(\"%s\"), []byte(\"%s\"), %v},\n",
			v.name, goEscape(data), goEscape(v.expected), v.huff)
	}
	huff, err := os.ReadFile(filepath.Join(filepath.Dir(srcFile()), "huffman_vectors.txt"))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	for _, line := range strings.Split(strings.TrimRight(string(huff), "\n"), "\n") {
		b.WriteString(line + "\n")
	}
	b.WriteString("}\n")

	outPath := filepath.Join(filepath.Dir(srcFile()), "..", "..", "parser", "xpress_test_data.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// srcFile returns the path of this source file.
func srcFile() string {
	_, file, _, _ := runtime.Caller(0)
	return file
}

// goEscape renders b as the body of a Go double-quoted string literal
// with \x escapes, matching the style of the original data file.
func goEscape(b []byte) string {
	var sb strings.Builder
	for _, x := range b {
		if x >= 0x20 && x <= 0x7e && x != '"' && x != '\\' {
			sb.WriteByte(x)
		} else {
			fmt.Fprintf(&sb, "\\x%02x", x)
		}
	}
	return sb.String()
}

// encode matches the MS-XCA 2.1.1 encode pseudocode verbatim.
func encode(data []byte) []byte {
	var out []byte
	flags := uint32(0)
	flagCount := 0
	flagOutPos := 0
	outPos := 0
	inPos := 0
	lastLenHalf := 0

	writeFlags := func() {
		for i := 0; i < 4; i++ {
			out[flagOutPos+i] = byte(flags >> (8 * i))
		}
		flagCount = 0
		flagOutPos = 0
	}
	put := func(x byte) {
		out = append(out, x)
		outPos++
	}

	n := len(data)
	for inPos < n {
		bestLen := 0
		bestOff := 0
		maxLen := n - inPos
		if maxLen > 65535 {
			maxLen = 65535
		}
		start := inPos - 8192
		if start < 0 {
			start = 0
		}
		for cand := start; cand < inPos; cand++ {
			l := 0
			for l < maxLen && data[cand+l] == data[inPos+l] {
				l++
			}
			if l > bestLen {
				bestLen = l
				bestOff = inPos - cand
			}
		}
		if bestLen < 3 || inPos+2 >= n {
			flags <<= 1
			flagCount++
			if flagCount == 1 {
				flagOutPos = outPos
				out = append(out, 0, 0, 0, 0)
				outPos += 4
			}
			put(data[inPos])
			inPos++
			if flagCount == 32 {
				writeFlags()
			}
			continue
		}
		matchLen := bestLen - 3
		matchOff := bestOff - 1
		matchOff <<= 3
		if matchLen < 7 {
			tok := matchOff + matchLen
			put(byte(tok))
			put(byte(tok >> 8))
		} else {
			tok := matchOff | 7
			put(byte(tok))
			put(byte(tok >> 8))
			matchLen -= 7
			if lastLenHalf == 0 {
				lastLenHalf = outPos
				if matchLen < 15 {
					put(byte(matchLen))
				} else {
					put(15)
					goto encodeExtraLen
				}
			} else {
				if matchLen < 15 {
					out[lastLenHalf] |= byte(matchLen << 4)
					lastLenHalf = 0
				} else {
					out[lastLenHalf] |= 15 << 4
					lastLenHalf = 0
					goto encodeExtraLen
				}
			}
			goto afterLen
		encodeExtraLen:
			matchLen -= 15
			if matchLen < 255 {
				put(byte(matchLen))
			} else {
				put(255)
				matchLen += 7 + 15
				if matchLen < 1<<16 {
					put(byte(matchLen))
					put(byte(matchLen >> 8))
				} else {
					put(0)
					put(0)
					put(byte(matchLen))
					put(byte(matchLen >> 8))
					put(byte(matchLen >> 16))
					put(byte(matchLen >> 24))
				}
			}
		afterLen:
			_ = matchLen
		}
		flags = (flags << 1) | 1
		flagCount++
		if flagCount == 32 {
			writeFlags()
		}
		inPos += bestLen
	}
	if flagCount > 0 {
		flags <<= uint(32 - flagCount)
		flags |= (1 << uint(32-flagCount)) - 1
		for i := 0; i < 4; i++ {
			out[flagOutPos+i] = byte(flags >> (8 * i))
		}
	}
	return out
}

func plainVectors() []vector {
	return []vector{
		{
			name:     "Plain0: all literals",
			input:    []byte("GHOST//RECOVER data recovery engineer.\n"),
			expected: []byte("GHOST//RECOVER data recovery engineer.\n"),
		},
		{
			name:     "Plain1: the MS-XCA worked example, 100 copies of abc",
			input:    bytes.Repeat([]byte("abc"), 100),
			expected: bytes.Repeat([]byte("abc"), 100),
		},
		{
			name:     "Plain2: nibble-encoded length (49 copies of P)",
			input:    bytes.Repeat([]byte("P"), 49),
			expected: bytes.Repeat([]byte("P"), 49),
		},
		{
			name:     "Plain3: byte-encoded length (300 copies of A)",
			input:    bytes.Repeat([]byte("A"), 300),
			expected: bytes.Repeat([]byte("A"), 300),
		},
		{
			name:     "Plain4: LE16 length (4002 copies of Q)",
			input:    bytes.Repeat([]byte("Q"), 4002),
			expected: bytes.Repeat([]byte("Q"), 4002),
		},
		{
			name:     "Plain5: two matches in one flag group",
			input:    bytes.Repeat([]byte("abcdefghij"), 30),
			expected: bytes.Repeat([]byte("abcdefghij"), 30),
		},
		{
			name:     "Plain6: shared half-byte between two matches",
			input:    append(bytes.Repeat([]byte("abcdefghij"), 2), bytes.Repeat([]byte("xy"), 12)...),
			expected: append(bytes.Repeat([]byte("abcdefghij"), 2), bytes.Repeat([]byte("xy"), 12)...),
		},
		{
			name:     "Plain7: literal between two shared-nibble matches",
			input:    append(append(bytes.Repeat([]byte("mnop"), 8), 'Z'), bytes.Repeat([]byte("mnop"), 8)...),
			expected: append(append(bytes.Repeat([]byte("mnop"), 8), 'Z'), bytes.Repeat([]byte("mnop"), 8)...),
		},
		{
			name:     "Plain8: LE32 length (70000 copies of W)",
			input:    bytes.Repeat([]byte("W"), 70000),
			expected: bytes.Repeat([]byte("W"), 70000),
		},
		{
			name:     "Plain9: large offset (6000 copies of a 22-byte phrase)",
			input:    bytes.Repeat([]byte("0123456789abcdefghijkl"), 6000),
			expected: bytes.Repeat([]byte("0123456789abcdefghijkl"), 6000),
		},
	}
}

func extraPlainVectors() []vector {
	var v []vector
	for l := 11; l <= 24; l++ {
		v = append(v, vector{
			name:     fmt.Sprintf("PlainNib%d: length %d", l-10, l),
			input:    bytes.Repeat([]byte("n"), l),
			expected: bytes.Repeat([]byte("n"), l),
		})
	}
	for _, l := range []int{26, 50, 100, 150, 200, 250, 279} {
		v = append(v, vector{
			name:     fmt.Sprintf("PlainByte%d: length %d", l-25, l),
			input:    bytes.Repeat([]byte("b"), l),
			expected: bytes.Repeat([]byte("b"), l),
		})
	}
	return v
}

func sharedHalfByteVector() vector {
	return vector{
		name: "PlainSharedHalfByteAcrossLiteral",
		input: []byte{
			0xff, 0xff, 0xff, 0x5f,
			0x41,       // 'A'
			0x07, 0x00, // match offset 1, shared-nibble form
			0x21,       // low nibble: length 11; high nibble: length 12 (next)
			0x42,       // 'B'
			0x07, 0x00, // match offset 1, uses high nibble of the byte above
		},
		expected:      append([]byte("AAAAAAAAAAAA"), []byte("BBBBBBBBBBBBB")...),
		precompressed: true,
	}
}

func anchorVector() vector {
	input := bytes.Repeat([]byte("A1B2C3D4E5F6G7H8"), 16)
	return vector{
		name:     "Anchor",
		input:    input,
		expected: input,
	}
}
